
services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin123
  #     POSTGRES_DB: gym
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #     - ./db/gym.sql:/docker-entrypoint-initdb.d/gym.sql
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    # depends_on:
    #   - db
    environment:
      FLASK_APP: app.py
    ports: 
      - "5000:5000"
volumes:
  db_data:
